### ISSUE TITLE
Error when running off-target example

### ISSUE THREAD

**Issue by jcollins6** [Lattice-Automation/primers#3]
I am getting the following error when trying to run the off-target example:

% primers AATGAGACAATAGCACACACAGCTAGGTCAGCATACGAAA -t ggaattacgtAATGAGACAATAGCACACACAGCTAGGTCAGCATACGAAAggaccagttacagga
Traceback (most recent call last):
  File "/opt/anaconda3/bin/primers", line 8, in <module>
    sys.exit(run())
  File "/opt/anaconda3/lib/python3.9/site-packages/primers/main.py", line 19, in run
    fwd, rev = primers(
  File "/opt/anaconda3/lib/python3.9/site-packages/primers/primers.py", line 258, in primers
    fwd_primers = _primers(
  File "/opt/anaconda3/lib/python3.9/site-packages/primers/primers.py", line 314, in _primers
    ot = offtargets(seq, offtarget_check)
  File "/opt/anaconda3/lib/python3.9/site-packages/primers/offtargets.py", line 34, in offtargets
    for m in mutate(check_seq[s : s + 10]):
  File "/opt/anaconda3/lib/python3.9/site-packages/primers/offtargets.py", line 29, in mutate
    for m in mutate_map[c]:
KeyError: 'g'

**Comment by jcollins6** [comment]
Found the error, it doesn't recognize lowercase bases

**Comment by jjti** [comment]
Hey there and thanks for pointing this out! This should be fixed in the latest version: https://github.com/Lattice-Automation/primers/commit/e19cca8b025a5d8e481176b0b73717f88b9e84b6

**Comment by jjti** [comment]
PS: please let me know if you see any issues! 0.2.8 is the version with the patch

**Comment by jcollins6** [comment]
that fixed the error, thanks!
