### ISSUE TITLE
released package on pypi don't contain `requirements.txt` which makes installation fail if not using `whl` file

### ISSUE THREAD

**Issue by TTTPOB** [Lattice-Automation/primers#6]
to reproduce
```
wget https://pypi.io/packages/source/p/primers/primers-0.5.4.tar.gz
tar zxvf primer*
cd primers-0.5.4
ls
```
got me
```
LICENSE
PKG-INFO
primers
primers.egg-info
README.md
setup.cfg
setup.py
tests
```

you see there is no `requirements.txt`, but [setup.py](https://github.com/Lattice-Automation/primers/blob/42fba95ee8462a7f12304ac39330fcd0f8f4e0b8/setup.py#L10) reads it.

thus got me
```
......
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  <string>:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Traceback (most recent call last):
    File "/tmp/primers-0.5.4/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/tmp/primers-0.5.4/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/primers-0.5.4/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-hoe006rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-hoe006rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-hoe006rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-hoe006rw/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 10, in <module>
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  error: subprocess-exited-with-error
......
```

the reason why I don't use wheel is that I am packing it to `bioconda` conda channel. patching it as temp workaround

**Comment by guzmanvig** [comment]
Done in the latest release.
